# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='title')),
                ('venue', models.CharField(max_length=100, verbose_name='venue of event')),
                ('n_stud', models.IntegerField(null=True, verbose_name='number of students')),
                ('n_fac', models.IntegerField(null=True, verbose_name='number of faculty')),
                ('n_ind', models.IntegerField(null=True, verbose_name='number from industry')),
                ('date', models.DateField(verbose_name='date of event')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 770828, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'db_table': 'event',
                'ordering': ('-date_added',),
            },
        ),
    ]
