# Generated by Django 3.2.8 on 2022-01-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('AE', 'Aerospace Engineering'), ('BT', 'Biotechnology'), ('CE', 'Chemical Engineering'), ('CIV', 'Civil Engineering'), ('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EIE', 'Electronics and Instrumentation Engineering'), ('IEM', 'Industrial Engineering and Management'), ('ISE', 'Information Science and Engineering'), ('MCA', 'Master of Computer Applications'), ('ME', 'Mechanical Engineering'), ('ETE', 'Electronics and Telecommunication Engineering (Telecommunication Engineering)'), ('BSC', 'Basic Sciences')], default='ISE', max_length=3),
        ),
    ]
