# Generated by Django 3.2.8 on 2022-02-13 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='u_id',
            field=models.ManyToManyField(related_name='faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved'),
        ),
    ]
