# Generated by Django 4.0.1 on 2022-02-12 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('organisation', models.CharField(max_length=50, verbose_name='organisation')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 12, 13, 49, 24, 849705, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'achievement',
                'ordering': ('-date_added',),
            },
        ),
    ]
