# Generated by Django 3.2.8 on 2022-02-13 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 8, 18, 47, 591557, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
