# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100, verbose_name='activity')),
                ('date', models.DateField(verbose_name='date of activity')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 786838, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'verbose_name_plural': 'other activities',
                'db_table': 'other_activity',
                'ordering': ('-date_added',),
            },
        ),
    ]
