# Generated by Django 3.2.8 on 2022-02-13 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 14, 31, 56, 833170, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
