# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industrial_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100, verbose_name='purpose of visit')),
                ('industry', models.CharField(max_length=50, verbose_name='industry')),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='semester')),
                ('n_stud', models.IntegerField(null=True, verbose_name='no. of students')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 786838, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'verbose_name_plural': 'industrial visits',
                'db_table': 'industrial_visit',
                'ordering': ('-date_added',),
            },
        ),
    ]
