# Generated by Django 3.2.8 on 2022-02-13 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('topic', models.CharField(max_length=50, verbose_name='topic')),
                ('status', models.CharField(blank=True, choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('ON', 'Ongoing')], max_length=3, null=True, verbose_name='status')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 6, 36, 26, 441749, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ManyToManyField(related_name='patents_faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'patent',
                'ordering': ('-date_added',),
            },
        ),
    ]
