# Generated by Django 3.2.8 on 2022-02-13 08:18

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_isbn', models.IntegerField(unique=True, verbose_name='ISBN #')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('publisher', models.CharField(max_length=50, verbose_name='publisher')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 8, 18, 47, 591557, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ManyToManyField(related_name='books_faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'book',
                'ordering': ('-date_added',),
            },
        ),
    ]
