# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_isbn', models.IntegerField(unique=True, verbose_name='ISBN #')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('publisher', models.CharField(max_length=50, verbose_name='publisher')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 786838, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'db_table': 'book',
                'ordering': ('-date_added',),
            },
        ),
    ]
