# Generated by Django 3.2.8 on 2022-02-13 11:00

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industrial_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100, verbose_name='purpose of visit')),
                ('industry', models.CharField(max_length=50, verbose_name='industry')),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='semester')),
                ('n_stud', models.IntegerField(blank=True, null=True, verbose_name='no. of students')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 10, 59, 59, 561364, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ManyToManyField(related_name='industrial_visits_faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'industrial_visit',
                'ordering': ('-date_added',),
            },
        ),
    ]
