# Generated by Django 3.2.8 on 2022-02-13 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrial_visit',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'industrial visits'},
        ),
        migrations.AlterField(
            model_name='industrial_visit',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 13, 51, 5, 570716, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
