# Generated by Django 3.2.8 on 2022-02-13 03:47

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='name of event')),
                ('venue', models.CharField(max_length=100, verbose_name='venue')),
                ('date', models.DateField(verbose_name='date of event')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 3, 47, 11, 558991, tzinfo=utc), verbose_name='recorded date')),
                ('u_id', models.ManyToManyField(related_name='workshops_faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'Workshop',
                'ordering': ('-date_added',),
            },
        ),
    ]
