# Generated by Django 4.0.1 on 2022-02-11 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 13, 44, 19, 196178, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
