# Generated by Django 4.0.1 on 2022-01-12 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('sanc_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.IntegerField(default=2022)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 1, 12, 15, 6, 42, 3283, tzinfo=utc))),
                ('CO_PI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_coprinvestigated', to=settings.AUTH_USER_MODEL)),
                ('PI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_prinvestigated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
