# Generated by Django 3.2.8 on 2022-01-17 11:25

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('sanc_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2022)])),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 1, 17, 11, 25, 34, 193518, tzinfo=utc))),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
