# Generated by Django 3.2.8 on 2022-02-13 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='CO_PI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_coprinvestigated', to=settings.AUTH_USER_MODEL, verbose_name='co-principle investigator'),
        ),
        migrations.AddField(
            model_name='grant',
            name='PI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_prinvestigated', to=settings.AUTH_USER_MODEL, verbose_name='principle investigator'),
        ),
    ]
