# Generated by Django 4.0.1 on 2022-02-11 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 5, 7, 32, 174032, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
