# Generated by Django 3.2.8 on 2022-01-17 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grants',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 17, 11, 26, 34, 691755, tzinfo=utc)),
        ),
    ]
