# Generated by Django 4.0.1 on 2022-01-12 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_alter_grants_date_added_alter_grants_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grants',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 15, 36, 55, 684554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grants',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
