# Generated by Django 3.2.8 on 2022-01-14 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_alter_grants_date_added_alter_grants_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grants',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 5, 44, 39, 367316, tzinfo=utc)),
        ),
    ]
