# Generated by Django 3.2.8 on 2022-02-13 14:31

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=50, verbose_name='membership')),
                ('association', models.CharField(max_length=50, verbose_name='association')),
                ('term', models.IntegerField(blank=True, null=True, verbose_name='term of membership')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 14, 31, 56, 841169, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ManyToManyField(related_name='memberships_faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ('-date_added',),
            },
        ),
    ]
