# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=50, verbose_name='membership')),
                ('association', models.CharField(max_length=50, verbose_name='association')),
                ('term', models.IntegerField(null=True, verbose_name='term of membership')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 794832, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'db_table': 'membership',
                'ordering': ('-date_added',),
            },
        ),
    ]
