# Generated by Django 4.0.1 on 2022-02-11 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('fund_agency', models.CharField(max_length=50, verbose_name='agency funding consultancy')),
                ('rec_amt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sanctioned amount')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 11, 8, 57, 11, 118729, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultancy',
                'ordering': ('-date_added',),
            },
        ),
    ]
