# Generated by Django 3.2.8 on 2022-02-13 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('fund_agency', models.CharField(max_length=50, verbose_name='agency funding consultancy')),
                ('rec_amt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sanctioned amount')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 3, 47, 11, 558991, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'db_table': 'consultancy',
                'ordering': ('-date_added',),
            },
        ),
    ]
