# Generated by Django 3.2.8 on 2022-02-13 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consultancies', '0002_consultancy_f_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancy',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'consultancies'},
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 6, 36, 26, 430766, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
