# Generated by Django 3.2.8 on 2022-02-13 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consultancies', '0005_alter_consultancy_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 10, 59, 59, 545365, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
