# Generated by Django 4.0.1 on 2022-02-11 05:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('submitted_to', models.CharField(max_length=50, verbose_name='submitted')),
                ('budg_amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='budgetted amount')),
                ('status', models.CharField(blank=True, choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('ON', 'Ongoing')], max_length=3, null=True, verbose_name='status')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 11, 5, 7, 32, 174032, tzinfo=utc), verbose_name='recorded date')),
                ('CO_PI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_coprinvestigated', to=settings.AUTH_USER_MODEL, verbose_name='co-principle investigator')),
                ('PI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_prinvestigated', to=settings.AUTH_USER_MODEL, verbose_name='principle investigator')),
            ],
            options={
                'db_table': 'proposal',
                'ordering': ('-date_added',),
            },
        ),
    ]
