# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=50, unique=True, verbose_name='organisation')),
                ('mod_col', models.CharField(max_length=25, verbose_name='mode of collaboration')),
                ('validity', models.IntegerField(verbose_name='validity')),
                ('date', models.DateField(verbose_name='date of mou')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 794832, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'verbose_name_plural': 'MoUs',
                'db_table': 'mou',
                'ordering': ('-date_added',),
            },
        ),
    ]
