# Generated by Django 4.0.1 on 2022-02-13 15:24

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('agency', models.CharField(max_length=50, verbose_name='agency sanctioning grant')),
                ('sanc_amt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sanctioned amount')),
                ('year', models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2022)], verbose_name='year of sanction')),
                ('remarks', models.CharField(max_length=50, null=True, verbose_name='additional remarks')),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 15, 24, 49, 770828, tzinfo=utc), verbose_name='recorded date')),
            ],
            options={
                'db_table': 'grant',
                'ordering': ('-date_added',),
            },
        ),
    ]
