# Generated by Django 4.0.1 on 2022-02-11 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='topic')),
                ('res_person', models.CharField(max_length=50, verbose_name='resource person')),
                ('organisation', models.CharField(max_length=50, verbose_name='organisation')),
                ('n_stud', models.IntegerField(null=True, verbose_name='no. of students')),
                ('n_fac', models.IntegerField(null=True, verbose_name='no. of faculty')),
                ('n_ind', models.IntegerField(null=True, verbose_name='no. from industry')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 11, 13, 44, 19, 196178, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'lecture',
                'ordering': ('-date_added',),
            },
        ),
    ]
