# Generated by Django 4.0.1 on 2022-02-12 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_lecture_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 12, 13, 49, 24, 849705, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
