# Generated by Django 3.2.8 on 2022-02-13 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=50, unique=True, verbose_name='organisation')),
                ('mod_col', models.CharField(max_length=25, verbose_name='mode of collaboration')),
                ('validity', models.IntegerField(verbose_name='validity')),
                ('date', models.DateField(verbose_name='date of mou')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 13, 13, 51, 5, 578703, tzinfo=utc), verbose_name='recorded date')),
                ('u_id', models.ManyToManyField(related_name='mou_faculty_involved', to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'mous',
                'ordering': ('-date_added',),
            },
        ),
    ]
