# Generated by Django 3.2.8 on 2022-02-13 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mou',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'MoUs'},
        ),
        migrations.AlterField(
            model_name='mou',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 14, 31, 56, 841169, tzinfo=utc), verbose_name='recorded date'),
        ),
    ]
