# Generated by Django 4.0.1 on 2022-02-12 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='topic')),
                ('venue', models.CharField(max_length=100, verbose_name='venue')),
                ('n_stud', models.IntegerField(blank=True, null=True, verbose_name='no. of students')),
                ('n_fac', models.IntegerField(blank=True, null=True, verbose_name='no. of faculty')),
                ('n_ind', models.IntegerField(blank=True, null=True, verbose_name='no. from industry')),
                ('date', models.DateField(verbose_name='date of talk')),
                ('slug', models.SlugField(max_length=250)),
                ('date_added', models.DateField(default=datetime.datetime(2022, 2, 12, 10, 44, 28, 295606, tzinfo=utc), verbose_name='recorded date')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='faculty involved')),
            ],
            options={
                'db_table': 'talk',
                'ordering': ('-date_added',),
            },
        ),
    ]
